"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Plus } from "lucide-react";

const faqs = [
  {
    question: "What is Kryptos?",
    answer:
      "Kryptos is an AI-powered blockchain intelligence platform that scans wallets and smart contracts across 14 EVM-compatible chains. It returns a real-time risk score, surfacing scammers, mixer users, rug pulls, and suspicious on-chain patterns before you interact with them.",
  },
  {
    question: "Which blockchains does Kryptos support?",
    answer:
      "Kryptos currently supports 14 EVM-compatible chains including Ethereum, Polygon, BNB Smart Chain, Avalanche, Arbitrum, Optimism, Base, Fantom, Cronos, zkSync, Linea, Scroll, Mantle, and Celo. More chains are continuously being added.",
  },
  {
    question: "How is the risk score calculated?",
    answer:
      "Our risk score is generated by a multi-layered ML pipeline that combines on-chain transaction graph analysis, anomaly detection, MEV behavior patterns, token interactions, known scammer labels, sanctions screening, and cross-chain activity. The score ranges from 0 (safe) to 100 (high risk).",
  },
  {
    question: "Is Kryptos only for developers?",
    answer:
      "Not at all. Kryptos is built for anyone in Web3 — traders, DeFi users, DAO contributors, and developers alike. You don't need any technical background to run a wallet analysis. Simply paste a wallet address and get an instant risk report.",
  },
  {
    question: "Can I screen multiple wallets at once?",
    answer:
      "Yes. Kryptos offers a Bulk Screening feature that lets you submit a list of wallet addresses and receive risk reports for all of them in batch. This is particularly useful for token launchpads, DAOs, and compliance teams.",
  },
  {
    question: "Is my data kept private?",
    answer:
      "All analysis is performed on public on-chain data — Kryptos does not store or access any private keys or personal information. Wallet addresses submitted for analysis may be cached to improve performance, but are never shared with third parties.",
  },
  {
    question: "How do I get started?",
    answer:
      "Connect your wallet using the button in the hero section, or head directly to the Wallet Analyzer. You don't need to create an account — just paste any EVM wallet address and Kryptos will return a full risk report within seconds.",
  },
];

const FAQItem = ({ question, answer, index }: { question: string; answer: string; index: number }) => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-50px" }}
      transition={{ duration: 0.5, delay: index * 0.07 }}
      className={`border-b border-zinc-800 last:border-b-0`}
    >
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full flex items-center justify-between py-6 text-left group gap-6"
      >
        <span className="text-lg md:text-xl font-[family-name:var(--font-spacemono)] text-zinc-100 group-hover:text-white transition-colors leading-snug pr-4">
          {question}
        </span>
        <motion.span
          animate={{ rotate: isOpen ? 45 : 0 }}
          transition={{ duration: 0.25, ease: "easeInOut" }}
          className="flex-shrink-0 w-8 h-8 rounded-full border border-zinc-700 group-hover:border-green-500/50 flex items-center justify-center text-zinc-400 group-hover:text-green-400 transition-colors"
        >
          <Plus size={16} />
        </motion.span>
      </button>

      <AnimatePresence initial={false}>
        {isOpen && (
          <motion.div
            key="content"
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3, ease: "easeInOut" }}
            className="overflow-hidden"
          >
            <p className="pb-6 text-zinc-400 font-[family-name:var(--font-spacemono)] leading-relaxed text-base">
              {answer}
            </p>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};

const FAQ = () => {
  return (
    <section className="py-24 px-8 relative text-white">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.7 }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl md:text-7xl font-[family-name:var(--font-nuqun)] mb-6">
            Frequently Asked Questions
          </h2>
          <p className="text-zinc-400 text-lg font-[family-name:var(--font-spacemono)] max-w-xl mx-auto">
            Everything you need to know about Kryptos and how it works.
          </p>
        </motion.div>

        {/* FAQ Items */}
        <div className="bg-zinc-900/40 border border-zinc-800 rounded-3xl px-8 py-2 backdrop-blur-sm">
          {faqs.map((faq, i) => (
            <FAQItem key={i} index={i} question={faq.question} answer={faq.answer} />
          ))}
        </div>

        {/* Bottom CTA */}
        <motion.p
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.4 }}
          className="text-center mt-10 text-zinc-500 font-[family-name:var(--font-spacemono)] text-sm"
        >
          Still have questions?{" "}
          <a href="/contact" className="text-green-400 hover:text-green-300 transition-colors underline underline-offset-4">
            Contact us
          </a>
        </motion.p>
      </div>
    </section>
  );
};

export default FAQ;
