/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RiskRegistry } from "./RiskRegistry";
export * as factories from "./factories";
export { RiskRegistry__factory } from "./factories/RiskRegistry__factory";
