/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RiskRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "getReport" | "reports" | "storeReport"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ReportStored"): EventFragment;

  encodeFunctionData(
    functionFragment: "getReport",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "reports", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "storeReport",
    values: [BytesLike, BigNumberish, string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getReport", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "reports", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "storeReport",
    data: BytesLike
  ): Result;
}

export namespace ReportStoredEvent {
  export type InputTuple = [
    wallet: BytesLike,
    riskScore: BigNumberish,
    ipfsHash: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    wallet: string,
    riskScore: bigint,
    ipfsHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    wallet: string;
    riskScore: bigint;
    ipfsHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RiskRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): RiskRegistry;
  waitForDeployment(): Promise<this>;

  interface: RiskRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getReport: TypedContractMethod<
    [wallet: BytesLike],
    [
      [bigint, string, bigint] & {
        riskScore: bigint;
        ipfsHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  reports: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, bigint] & {
        riskScore: bigint;
        ipfsHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  storeReport: TypedContractMethod<
    [
      wallet: BytesLike,
      riskScore: BigNumberish,
      ipfsHash: string,
      timestamp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getReport"
  ): TypedContractMethod<
    [wallet: BytesLike],
    [
      [bigint, string, bigint] & {
        riskScore: bigint;
        ipfsHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "reports"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, bigint] & {
        riskScore: bigint;
        ipfsHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "storeReport"
  ): TypedContractMethod<
    [
      wallet: BytesLike,
      riskScore: BigNumberish,
      ipfsHash: string,
      timestamp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ReportStored"
  ): TypedContractEvent<
    ReportStoredEvent.InputTuple,
    ReportStoredEvent.OutputTuple,
    ReportStoredEvent.OutputObject
  >;

  filters: {
    "ReportStored(bytes32,uint8,string,uint64)": TypedContractEvent<
      ReportStoredEvent.InputTuple,
      ReportStoredEvent.OutputTuple,
      ReportStoredEvent.OutputObject
    >;
    ReportStored: TypedContractEvent<
      ReportStoredEvent.InputTuple,
      ReportStoredEvent.OutputTuple,
      ReportStoredEvent.OutputObject
    >;
  };
}
